name: Create Release and Upload ZIP on Folder Change

on:
  push:
    paths:
      - 'ספרים/**'  # Trigger on changes in this folder and its subfolders

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install zip (if not already installed)
    - name: Install zip
      run: sudo apt-get install zip

    # Zip the folder you want to include in the release
    - name: Create ZIP of folder
      run: zip -r ספרים.zip ספרים

    # Upload ZIP file as an asset to the release
    - name: Upload ZIP to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ספרים.zip
        tag: ${{ github.sha }}  # Use commit SHA for a unique tag
        token: ${{ secrets.GITHUB_TOKEN }}
