name: Create Release and Upload ZIP on Folder Change

on:
  push:
    paths:
      - 'ספרים/**'  # Trigger on changes in this folder and its subfolders

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create ZIP of folder
      run: zip -r ספרים.zip ספרים

    - name: Upload ZIP to GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ספרים.zip
        tag: ${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
        skipIfReleaseExists: true  # Optional, to prevent errors if the release already exists
